In [2]:
import numpy as np

In [3]:
l = [5,6,7,2,3]
n1 = np.array(l)

print n1
print type(n1) # n dimensional array
print n1.ndim # How many dimensions
print n1.shape # length

[5 6 7 2 3]
<type 'numpy.ndarray'>
1
(5,)


In [4]:
n2 = n1 + 5
print n2
n3 = n1 * 2
print n3

[10 11 12  7  8]
[10 12 14  4  6]


In [86]:
print n1
n2 = np.array([6,3,4,6,8])
print n1 + n2
print n2[-3]  # 3rd last
print n2[:3]  # first 3
print n2[0:4]  # first 4 elements
print n2[0::2]  # alternate element
print n2[::-1]  # reverse
print n2[[1,3,4]]  # selective/multiple indexing

[-1  8 -1  9 10]
[ 5 11  3 15 18]
4
[6 3 4]
[6 3 4 6]
[6 4 8]
[8 6 4 3 6]
[3 6 8]


In [64]:
print n1
n1[1] = 8  # replacing a value
print n1
n1[1:4] = [3,5,1]
print n1
n1[[1,3,4]] = [8,9,10]
print n1

[5 6 7 2 3]
[5 8 7 2 3]
[5 3 5 1 3]
[ 5  8  5  9 10]


In [77]:
print n1
print n1[n1 > 5]  # filtering
print n1[(n1 <= 5) | (n1 == 10)]  # multiple filtering
n1[n1 == 5] = -1  # filtering with assignments
print n1

[-1  8 -1  9 10]
[ 8  9 10]
[-1 -1 10]
[-1  8 -1  9 10]


In [92]:
n3 = np.array([10, 34, 2, 3, 6], dtype=np.int16)  # dtype is for each element
print n3.dtype  # returns datatype of each element
n4 = n3[[1,4]]
print n4

int16
[34  6]


In [98]:
n5 = np.array([6, 7, 3, 4], dtype=np.int16)
n6 = n5[1:3].copy()  # copying array to another variable instead referencing the view
print n6
n6[1] = 9
print n6
print n5

[7 3]
[7 9]
[6 7 3 4]


In [104]:
print n1
n1[n1 == -1] = 0
print n1

[ 0  8  0  9 10]
[ 0  8  0  9 10]


In [133]:
print n1
print n1.sum()
print n1.mean(
)
print n1.std()
print n1.var()
print n1.cumsum()
print n1.min()
print n1.max()
print n1.repeat(2)
# print n1.sort()
print n1[::-1] # sorting

[ 0  0  8  9 10]
27
5.4
4.45421149026
19.84
[ 0  0  8 17 27]
0
10
[ 0  0  0  0  8  8  9  9 10 10]
[10  9  8  0  0]


In [155]:
print np.arange(21)
print np.arange(9,19)
print np.arange(0,30,2) # (start, end, stepsize) here > even numbers
print np.random.rand(10)
print np.random.randint(20)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 9 10 11 12 13 14 15 16 17 18]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]
[ 0.3342971   0.14535867  0.08222852  0.68248348  0.11458073  0.14943139
  0.45302136  0.19681185  0.08729529  0.18825581]
5
